services:
  postgres:
    image: postgres:latest
    container_name: order-service
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: orders-ecommerce-app
    ports:
      - "5436:5432"
    volumes:
      - my_postgres_data:/var/lib/postgresql/data

volumes:
  my_postgres_data: