server:
  port: 8092

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/orders-ecommerce-app
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

product-service-api:
  url: http://localhost:8091