server:
  port: 8092

spring:
  kafka:
    producer:
      bootstrap-servers: localhost:9090
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderPlacedEvent:com.online.store.application.dto.kafka.OrderPlacedEvent
  datasource:
    url: jdbc:postgresql://localhost:5436/orders-ecommerce-app
    username: admin
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

product-service-api:
  url: http://localhost:8091